version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
  php:
    build: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www
    ports:
      - 8080:80
    depends_on:
      - db